import Foundation
let path="reports/working/build_detailed_report.swift"
var s=try String(contentsOfFile:path,encoding:.utf8)
s=s.replacingOccurrences(of:"reports/working/docx-package",with:"reports/working/detailed-docx-package")
s=s.replacingOccurrences(of:"reports/working/report.md",with:"reports/working/report-detailed.md")
s=s.replacingOccurrences(of:"reports/Holistic-Mind-Project-Report.docx",with:"reports/Holistic-Mind-Detailed-Final-Report.docx")
s=s.replacingOccurrences(of:"A Privacy-Conscious Mobile Wellness Application\\nwith Hybrid Practice Recommendations",with:"A Trauma-Informed Mobile Wellness Application\\nwith Explainable Hybrid Recommendations")
s=s.replacingOccurrences(of:"Student name: ______________________________",with:"Samyam Shrestha")
s=s.replacingOccurrences(of:"Student number: ____________________________",with:"BCU Student ID: 23189645")
s=s.replacingOccurrences(of:"Supervisor: _________________________________",with:"Supervisor: Rabin Ghimire")
s=s.replacingOccurrences(of:"Degree / course: _____________________________",with:"BSc (Hons) Computer and Data Science")
s=s.replacingOccurrences(of:"Institution: __________________________________",with:"Birmingham City University | Sunway College Kathmandu")
s=s.replacingOccurrences(of:"Submission date: ____________________________",with:"CMP6200 / DIG6200 | Individual Undergraduate Project")
s=s.replacingOccurrences(of:"11 figures · Academic references · Project-grounded evaluation",with:"15 figures · Requirements traceability · Technical evaluation")
s=s.replacingOccurrences(of:"body += para(\"Submission fields\",\"Heading2\")\nbody += para(\"Complete the cover metadata and add any institution-required declaration or acknowledgement before submission.\",\"SmallNote\")",with:"body += para(\"Evidence basis\",\"Heading2\")\nbody += para(\"Prior project submissions, current source, saved benchmarks, and dated verification records. Proposed user studies are distinguished from completed technical evaluation.\",\"SmallNote\")")
s=s.replacingOccurrences(of:"body += nav(\"Table 1. Saved journal-free ONNX benchmark\",\"table1\")",with:"for (i,b) in blocks.filter({$0.hasPrefix(\"@table|\")}).enumerated(){body += nav(String(b.components(separatedBy:\"\\n\")[0].dropFirst(7)),\"table\\(i+1)\")}")
s=s.replacingOccurrences(of:"var chapterIndex=0",with:"var chapterIndex=0\nvar tableCount=0")
s=s.replacingOccurrences(of:"let lines=b.components(separatedBy:\"\\n\");body += para(String(lines[0].dropFirst(7)),\"Caption\",\"<w:keepNext/>\",\"table1\")",with:"tableCount += 1;let lines=b.components(separatedBy:\"\\n\");body += para(String(lines[0].dropFirst(7)),\"Caption\",\"<w:keepNext/>\",\"table\\(tableCount)\")")
s=s.replacingOccurrences(of:"para(\"Source: Holistic Mind project (2026b), saved production-suite ONNX evaluation.\",\"TableSource\")",with:"para(tableCount == 3 ? \"Source: Holistic Mind project (2026b), saved production-suite ONNX evaluation.\" : \"Source: Project submissions and repository evidence; interpretation described in the surrounding section.\",\"TableSource\")")
s=s.replacingOccurrences(of:"A Privacy-Conscious Mobile Wellness Application",with:"A Trauma-Informed Mobile Wellness Application")
s=s.replacingOccurrences(of:"style(\"Navigation\",\"Navigation\",22,0,180",with:"style(\"Navigation\",\"Navigation\",20,0,100")
s=s.replacingOccurrences(of:"style(\"CoverDescriptor\",\"Cover Descriptor\",24,100,800",with:"style(\"CoverDescriptor\",\"Cover Descriptor\",24,100,650")
s=s.replacingOccurrences(of:"style(\"Caption\",\"Caption\",19,80,180",with:"style(\"Caption\",\"Caption\",19,80,180")
try s.write(toFile:path,atomically:true,encoding:.utf8)
